@startuml

hide empty description

[*] --> QUIET : System Start

QUIET -[#green]-> BUZZ_1 #green : <color:green>10 < DISTANCE (cm) ≤ 15
QUIET -[#orange]-> BUZZ_2 #orange : <color:orange>5 < DISTANCE (cm) ≤ 10
QUIET -[#red]-> BUZZ_3 #red : <color:red>0 < DISTANCE (cm) ≤ 5

BUZZ_1 --> QUIET : 15 < DISTANCE (cm)
BUZZ_1 -[#orange]-> BUZZ_2 #orange : <color:orange>5 < DISTANCE (cm) ≤ 10
BUZZ_1 -[#red]-> BUZZ_3 #red : <color:red>0 < DISTANCE (cm) ≤ 5

BUZZ_2 --> QUIET : 15 < DISTANCE (cm)
BUZZ_2 -[#green]-> BUZZ_1 #green : <color:green>10 < DISTANCE (cm) ≤ 15
BUZZ_2 -[#red]-> BUZZ_3 #red : <color:red>0 < DISTANCE (cm) ≤ 5

BUZZ_3 --> QUIET : 15 < DISTANCE (cm)
BUZZ_3 -[#green]-> BUZZ_1 #green : <color:green>10 < DISTANCE (cm) ≤ 15
BUZZ_3 -[#orange]-> BUZZ_2 #orange : <color:orange>5 < DISTANCE (cm) ≤ 10

@enduml
